package com.example.multilink.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF002C38)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF1A424F)
val onPrimaryContainerLight = Color(0xFF88AEBD)
val secondaryLight = Color(0xFF526167)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6E5EC)
val onSecondaryContainerLight = Color(0xFF58676D)
val tertiaryLight = Color(0xFF31203E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF483655)
val onTertiaryContainerLight = Color(0xFFB7A0C5)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FA)
val onBackgroundLight = Color(0xFF1A1C1D)
val surfaceLight = Color(0xFFF9F9FA)
val onSurfaceLight = Color(0xFF1A1C1D)
val surfaceVariantLight = Color(0xFFDDE3E7)
val onSurfaceVariantLight = Color(0xFF41484B)
val outlineLight = Color(0xFF71787B)
val outlineVariantLight = Color(0xFFC1C7CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3132)
val inverseOnSurfaceLight = Color(0xFFF1F0F1)
val inversePrimaryLight = Color(0xFFA6CDDC)
val surfaceDimLight = Color(0xFFDADADB)
val surfaceBrightLight = Color(0xFFF9F9FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3F4)
val surfaceContainerLight = Color(0xFFEEEEEF)
val surfaceContainerHighLight = Color(0xFFE8E8E9)
val surfaceContainerHighestLight = Color(0xFFE2E2E3)






val primaryLightMediumContrast = Color(0xFF002C38)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1A424F)
val onPrimaryContainerLightMediumContrast = Color(0xFFB0D7E7)
val secondaryLightMediumContrast = Color(0xFF2B383E)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF616F75)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF31203E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF483655)
val onTertiaryContainerLightMediumContrast = Color(0xFFE1C8EF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9FA)
val onBackgroundLightMediumContrast = Color(0xFF1A1C1D)
val surfaceLightMediumContrast = Color(0xFFF9F9FA)
val onSurfaceLightMediumContrast = Color(0xFF0F1112)
val surfaceVariantLightMediumContrast = Color(0xFFDDE3E7)
val onSurfaceVariantLightMediumContrast = Color(0xFF31373A)
val outlineLightMediumContrast = Color(0xFF4D5357)
val outlineVariantLightMediumContrast = Color(0xFF676E71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3132)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F0F1)
val inversePrimaryLightMediumContrast = Color(0xFFA6CDDC)
val surfaceDimLightMediumContrast = Color(0xFFC6C6C7)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9FA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF4F3F4)
val surfaceContainerLightMediumContrast = Color(0xFFE8E8E9)
val surfaceContainerHighLightMediumContrast = Color(0xFFDDDDDE)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D2)





val primaryLightHighContrast = Color(0xFF002C38)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF1A424F)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF202E33)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF3D4B51)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF31203E)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF483655)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9FA)
val onBackgroundLightHighContrast = Color(0xFF1A1C1D)
val surfaceLightHighContrast = Color(0xFFF9F9FA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDDE3E7)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF272D30)
val outlineVariantLightHighContrast = Color(0xFF434A4D)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3132)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFA6CDDC)
val surfaceDimLightHighContrast = Color(0xFFB8B9BA)
val surfaceBrightLightHighContrast = Color(0xFFF9F9FA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F0F1)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E3)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D4D5)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6C7)






val primaryDark = Color(0xFFA6CDDC)
val onPrimaryDark = Color(0xFF093542)
val primaryContainerDark = Color(0xFF1A424F)
val onPrimaryContainerDark = Color(0xFF88AEBD)
val secondaryDark = Color(0xFFBAC9D0)
val onSecondaryDark = Color(0xFF253238)
val secondaryContainerDark = Color(0xFF3B494F)
val onSecondaryContainerDark = Color(0xFFA9B7BE)
val tertiaryDark = Color(0xFFD6BEE4)
val onTertiaryDark = Color(0xFF3B2947)
val tertiaryContainerDark = Color(0xFF483655)
val onTertiaryContainerDark = Color(0xFFB7A0C5)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121415)
val onBackgroundDark = Color(0xFFE2E2E3)
val surfaceDark = Color(0xFF121415)
val onSurfaceDark = Color(0xFFE2E2E3)
val surfaceVariantDark = Color(0xFF41484B)
val onSurfaceVariantDark = Color(0xFFC1C7CB)
val outlineDark = Color(0xFF8B9295)
val outlineVariantDark = Color(0xFF41484B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E3)
val inverseOnSurfaceDark = Color(0xFF2F3132)
val inversePrimaryDark = Color(0xFF3E6471)
val surfaceDimDark = Color(0xFF121415)
val surfaceBrightDark = Color(0xFF38393A)
val surfaceContainerLowestDark = Color(0xFF0C0E0F)
val surfaceContainerLowDark = Color(0xFF1A1C1D)
val surfaceContainerDark = Color(0xFF1E2021)
val surfaceContainerHighDark = Color(0xFF282A2B)
val surfaceContainerHighestDark = Color(0xFF333536)





val primaryDarkMediumContrast = Color(0xFFBBE2F3)
val onPrimaryDarkMediumContrast = Color(0xFF002A35)
val primaryContainerDarkMediumContrast = Color(0xFF7096A5)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD0DFE6)
val onSecondaryDarkMediumContrast = Color(0xFF1A282D)
val secondaryContainerDarkMediumContrast = Color(0xFF849399)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFEDD3FB)
val onTertiaryDarkMediumContrast = Color(0xFF2F1F3C)
val tertiaryContainerDarkMediumContrast = Color(0xFF9F89AC)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121415)
val onBackgroundDarkMediumContrast = Color(0xFFE2E2E3)
val surfaceDarkMediumContrast = Color(0xFF121415)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF41484B)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD7DDE1)
val outlineDarkMediumContrast = Color(0xFFACB3B6)
val outlineVariantDarkMediumContrast = Color(0xFF8B9195)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E3)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2B)
val inversePrimaryDarkMediumContrast = Color(0xFF264D5A)
val surfaceDimDarkMediumContrast = Color(0xFF121415)
val surfaceBrightDarkMediumContrast = Color(0xFF434546)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF060808)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1E1F)
val surfaceContainerDarkMediumContrast = Color(0xFF262829)
val surfaceContainerHighDarkMediumContrast = Color(0xFF313334)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3E3F)





val primaryDarkHighContrast = Color(0xFFDBF4FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA2C9D8)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D13)
val secondaryDarkHighContrast = Color(0xFFE3F2F9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB6C5CC)
val onSecondaryContainerDarkHighContrast = Color(0xFF020D12)
val tertiaryDarkHighContrast = Color(0xFFFAEBFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD2BAE0)
val onTertiaryContainerDarkHighContrast = Color(0xFF130420)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF121415)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E3)
val surfaceDarkHighContrast = Color(0xFF121415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF41484B)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEBF1F4)
val outlineVariantDarkHighContrast = Color(0xFFBDC4C7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF264D5A)
val surfaceDimDarkHighContrast = Color(0xFF121415)
val surfaceBrightDarkHighContrast = Color(0xFF4F5051)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1E2021)
val surfaceContainerDarkHighContrast = Color(0xFF2F3132)
val surfaceContainerHighDarkHighContrast = Color(0xFF3A3C3D)
val surfaceContainerHighestDarkHighContrast = Color(0xFF454748)






val customColor1Light = Color(0xFF77459F)
val onCustomColor1Light = Color(0xFFFFFFFF)
val customColor1ContainerLight = Color(0xFF925EBA)
val onCustomColor1ContainerLight = Color(0xFFFFFBFF)

val customColor1LightMediumContrast = Color(0xFF4F1A76)
val onCustomColor1LightMediumContrast = Color(0xFFFFFFFF)
val customColor1ContainerLightMediumContrast = Color(0xFF8A56B2)
val onCustomColor1ContainerLightMediumContrast = Color(0xFFFFFFFF)

val customColor1LightHighContrast = Color(0xFF440B6B)
val onCustomColor1LightHighContrast = Color(0xFFFFFFFF)
val customColor1ContainerLightHighContrast = Color(0xFF63308B)
val onCustomColor1ContainerLightHighContrast = Color(0xFFFFFFFF)

val customColor1Dark = Color(0xFFE1B6FF)
val onCustomColor1Dark = Color(0xFF481270)
val customColor1ContainerDark = Color(0xFFB07AD9)
val onCustomColor1ContainerDark = Color(0xFF320054)

val customColor1DarkMediumContrast = Color(0xFFEED2FF)
val onCustomColor1DarkMediumContrast = Color(0xFF3C0064)
val customColor1ContainerDarkMediumContrast = Color(0xFFB07AD9)
val onCustomColor1ContainerDarkMediumContrast = Color(0xFF000000)

val customColor1DarkHighContrast = Color(0xFFFAEBFF)
val onCustomColor1DarkHighContrast = Color(0xFF000000)
val customColor1ContainerDarkHighContrast = Color(0xFFDEB1FF)
val onCustomColor1ContainerDarkHighContrast = Color(0xFF16002A)

